name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  calculate_version:
    name: Calculate version information
    runs-on: ubuntu-latest
    steps:
      - name: Get the sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Extract Docker Tag
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          tag2="${tag:1}"
          short=$(git rev-parse --short HEAD)
          final="${tag2/alpha/$short}"
          echo "GIT_TAG=${final}" >> $GITHUB_ENV
    outputs:
      git_tag: ${{ env.GIT_TAG }}
  build_and_push:
    uses: jasongdove/tvrename/.github/workflows/docker.yml@main
    needs: calculate_version
    with:
      base_version: develop
      info_version: ${{ needs.calculate_version.outputs.git_tag }}
      tag_version: ${{ github.sha }}
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
